python3 experimento_pyr_kimore_original.py > Results/exp1.txt
python3 experimento_pyr_kimore_original.py > Results/exp2.txt
python3 experimento_pyr_kimore_original.py > Results/exp3.txt
python3 experimento_pyr_kimore_original.py > Results/exp4.txt
python3 experimento_pyr_kimore_original.py > Results/exp5.txt
python3 experimento_pyr_kimore_original.py > Results/exp6.txt
python3 experimento_pyr_kimore_original.py > Results/exp7.txt
python3 experimento_pyr_kimore_original.py > Results/exp8.txt
python3 experimento_pyr_kimore_original.py > Results/exp9.txt
python3 experimento_pyr_kimore_original.py > Results/exp10.txt
